alumini/urls.py
from django.conf.urls import url
from . import views

app_name = 'alumini'

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

course/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'course'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	]



	

current/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'current'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	]



	

home/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'home'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	]



	

matrix/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('home.urls')),
    url(r'^course/',include('course.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^alumini/',include('alumini.urls')),
    url(r'^current/',include('current.urls')),
]

alumini/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models

# Create your models here.

current/models.py
from django.db import models

# Create your models here.

alumini/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
	return render(request, 'alumini/index.html')

course/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
	return render(request, 'course/index.html')

current/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
	return render(request, 'current/index.html')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
	return render(request, 'home/index.html')

alumini/templates/alumini/index.html
<!DOCTYPE HTML>

<html>
	<head>
	{% load staticfiles %}
		<title>Matrix-Alumini</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{%static 'assets/css/main.css'%}" />

	</head>
	<body>
	{% load staticfiles %}

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Matrix <span>IIT Guwahati</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'home:index'%}">Home</a></li>
					<li><a href="{% url 'alumini:index'%}">alumini</a></li>
					<li><a href="{% url 'current:index'%}">current</a></li>
					<li><a href="{% url 'course:index'%}">course</a></li>
				</ul>
			</nav>

		<h1><p><center>this is the Alumini page</center></p></h1>

		<!-- Scripts -->
			<script src="{%static 'assets/js/jquery.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{%static 'assets/js/skel.min.js' %}"></script>
			<script src="{%static 'assets/js/util.js' %}"></script>
			<script src="{%static 'assets/js/main.js' %}"></script>

	</body>
</html>

course/templates/course/index.html
<!DOCTYPE HTML>

<html>
	<head>
	{% load staticfiles %}
		<title>Matrix-Courses</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{%static 'assets/css/main.css'%}" />

	</head>
	<body>
	{% load staticfiles %}

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Matrix <span>IIT Guwahati</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'home:index'%}">Home</a></li>
					<li><a href="{% url 'alumini:index'%}">alumini</a></li>
					<li><a href="{% url 'current:index'%}">current</a></li>
					<li><a href="{% url 'course:index'%}">course</a></li>
				</ul>
			</nav>

		<h1><p><center>this is the course page</center></p></h1>

		<!-- Scripts -->
			<script src="{%static 'assets/js/jquery.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{%static 'assets/js/skel.min.js' %}"></script>
			<script src="{%static 'assets/js/util.js' %}"></script>
			<script src="{%static 'assets/js/main.js' %}"></script>

	</body>
</html>

current/templates/current/index.html
<!DOCTYPE HTML>

<html>
	<head>
	{% load staticfiles %}
		<title>Matrix-Current</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{%static 'assets/css/main.css'%}" />

	</head>
	<body>
	{% load staticfiles %}

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Matrix <span>IIT Guwahati</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'home:index'%}">Home</a></li>
					<li><a href="{% url 'alumini:index'%}">alumini</a></li>
					<li><a href="{% url 'current:index'%}">current</a></li>
					<li><a href="{% url 'course:index'%}">course</a></li>
				</ul>
			</nav>

		<h1><p><center>this is the current page</center></p></h1>

		<!-- Scripts -->
			<script src="{%static 'assets/js/jquery.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{%static 'assets/js/skel.min.js' %}"></script>
			<script src="{%static 'assets/js/util.js' %}"></script>
			<script src="{%static 'assets/js/main.js' %}"></script>

	</body>
</html>

home/templates/home/index.html
<!DOCTYPE HTML>

<html>
	<head>
	{% load staticfiles %}
		<title>Matrix</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{%static 'assets/css/main.css'%}" />

	</head>
	<body>
	{% load staticfiles %}

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Matrix <span>IIT Guwahati</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'home:index'%}">Home</a></li>
					<li><a href="{% url 'alumini:index'%}">alumini</a></li>
					<li><a href="{% url 'current:index'%}">current</a></li>
					<li><a href="{% url 'course:index'%}">course</a></li>
				</ul>
			</nav>

		<!-- Banner -->
		<!--
			Note: To show a background image, set the "data-bg" attribute below
			to the full filename of your image. This is used in each section to set
			the background image.
		-->
			<section id="banner" class="bg-img" data-bg="{%static 'images/banner.jpg'%}">
				<div class="inner">
					<header>
						<h1>This is Matrix</h1>
						<h3>Department of Mathematics, IIT Guwahati</h3>
					</header>
				</div>
				<a href="#one" class="more">Learn More</a>
			</section>

		<!-- One -->
			<section id="one" class="wrapper post bg-img" data-bg="{%static 'images/banner.jpg'%}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>head1</h2>
							<p>01.01.2017</p>
						</header>
						<div class="content">
							<p>this is some para.</p>
						</div>
						<footer>
							<a href="{% url 'alumini:index'%}" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
				<a href="#two" class="more">Learn More</a>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper post bg-img" data-bg="{%static 'images/banner.jpg'%}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>head2</h2>
							<p>12.21.2016</p>
						</header>
						<div class="content">
							<p>this is also a para.</p>
						</div>
						<footer>
							<a href="{% url 'current:index'%}" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
				<a href="#three" class="more">Learn More</a>
			</section>

		<!-- Three -->
			<section id="three" class="wrapper post bg-img" data-bg="{%static 'images/banner.jpg'%}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>head3</h2>
							<p>11.11.2016</p>
						</header>
						<div class="content">
							<p>this is also a para</p>
						</div>
						<footer>
							<a href="{% url 'course:index'%}" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
				<a href="#four" class="more">Learn More</a>
			</section>

		<!-- Four -->
			<section id="four" class="wrapper post bg-img" data-bg="{%static 'images/banner.jpg'%}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>head4</h2>
							<p>10.30.2016</p>
						</header>
						<div class="content">
							<p>this seriously is another para.</p>
						</div>
						<footer>
							<a href="{% url 'home:index'%}" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h2>Contact Me</h2>

					<form action="#" method="post">

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<ul class="icons">
						<li><a href="#" class="icon round fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon round fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon round fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>

					<div class="copyright">
						&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
					</div>

				</div>
			</footer>

		<!-- Scripts -->
			<script src="{%static 'assets/js/jquery.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{%static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{%static 'assets/js/skel.min.js' %}"></script>
			<script src="{%static 'assets/js/util.js' %}"></script>
			<script src="{%static 'assets/js/main.js' %}"></script>

	</body>
</html>